site_name: Eryx Documentation
site_description: Official documentation for the Eryx programming language
site_url: https://ImShyMike.github.io/Eryx/
site_author: ImShyMike
repo_url: https://github.com/ImShyMike/Eryx
repo_name: ImShyMike/Eryx
copyright: Copyright &copy; 2024 ImShyMike

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Language Features: language-features.md
  - CLI: cli.md
  - Examples: examples.md

theme:
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  name: material
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Fira Code
  logo: assets/eryx.png
  favicon: assets/eryx.ico

markdown_extensions:
  - tables
  - admonition
  - abbr
  - def_list
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ImShyMike
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/Eryx/

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
